name: CI ACTIONS
permissions: write-all
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: ['7.0']
    steps:
      - uses: actions/checkout@v4
        with:
          ref: develop
      - name: Merge changes into develop
        if: github.event_name == 'pull_request'
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          PR_BRANCH=${{ github.head_ref }}
          echo "Merging changes from branch $PR_BRANCH into develop"
          git fetch origin $PR_BRANCH
          git merge --no-ff origin/$PR_BRANCH
      - name: Install Python 3.10.15
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.15

      - name: Install dependencies
        run: |
          pip install pytest-cov coveralls
          pip install coverage
          pip install -r requirements.txt
          echo requirements installed

      - name: Run tests with Coverage
        run: |
          cd Code/tests
          coverage run -m pytest
          coveralls --service=github-actions
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      
      - name: Run autopep8
        if: github.ref == 'refs/heads/develop'
        id: autopep8
        uses: peter-evans/autopep8@v2
        with:
          args: --exit-code --recursive --in-place --aggressive .

      - name: set up pylint badge
        uses: Silleellie/pylint-github-action@v2
        with:
          lint-path: Code 

      - name: Update README.md with latest run and commit autopep 8 changes
        if: github.ref == 'refs/heads/develop'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git pull --rebase
          sed -i "s|(https://github.com/CSC510-GROUP-40/MovieRecommender/actions/runs.*)|(https://github.com/CSC510-GROUP-40/MovieRecommender/actions/runs/${{ github.run_id }})|" README.md
          git commit -am "Automated autopep8 fixes and Update README.md with the latest run ID"
          git push -f

