# name: Code Coverage

# on: [push]

# jobs:
#   upload-coverage:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: 3.8 

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install pandas
#           pip install pylint
#           pip install -U Flask
#           pip install -U flask-cors
#           pip install pytest
#           pip install pytest-cov

#       - name: Run tests and generate coverage
#         run: |
#           cd test
#           coverage run -m -a test_search
#           coverage run -m -a tests

#       - name: Upload coverage report to Codecov
#         run: |
#           bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}



name: Code Coverage

on: [push, pull_request]

jobs:
  upload-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Specify your Python version here

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools wheel  # Install setuptools and wheel

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov  # Install pytest and coverage tools

      - name: Run tests and generate coverage
        run: |
          pytest --cov=./Code/recommenderapp --cov-report=xml:coverage.xml  # Adjust path as needed

      - name: Upload coverage report to Codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          bash <(curl -s https://codecov.io/bash) -f coverage.xml
