name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Replace with your specific Python version

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools wheel  # Install setuptools and wheel

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Unit Tests and Save Output
      run: |
        mkdir -p test_outputs  # Create a directory to store output files
        for test_file in $(find test -name "test_*.py"); do
          test_name=$(basename "$test_file" .py)
          python -m unittest "$test_file" > "test_outputs/${test_name}_output.txt"
        done
      shell: bash

    - name: Upload Test Outputs
      uses: actions/upload-artifact@v3
      with:
        name: unit-test-outputs
        path: test_outputs/
